Fronted/WEB/Web.Docentes/Models/ErrorViewModel.cs
namespace Web.Docentes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Fronted/WEB/Web.Docentes/Models/MetaGlobal.cs
namespace Web.Docentes.Models
{
    public class MetaGlobal
    {
        //PARA RUTA APIS
        public static string RutaApiVenta = "";



        //PARA ACCESO A CONTROLES API
        public static string RutaApiVentaRol = "Api/Docente";
    }
}

Fronted/WEB/Web.Docentes/Models/PaginatedList.cs
namespace Web.Docentes.Models
{
    public class PaginatedList<T> : List<T>
    {
        public int PageIndex { get; private set; }
        public int TotalPages { get; private set; }

        public PaginatedList(List<T> items, int count, int pageIndex, int pageSize)
        {
            PageIndex = pageIndex;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);

            this.AddRange(items);
        }

        public bool HasPreviousPage => PageIndex > 1;

        public bool HasNextPage => PageIndex < TotalPages;

        public static PaginatedList<T> CreateAsync(IEnumerable<T> source, int pageIndex, int pageSize)
        {
            var count = source.Count();
            var items = source.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
            return new PaginatedList<T>(items, count, pageIndex, pageSize);
        }
    }
}

Fronted/WEB/Web.Docentes/Controllers/DocenteController.cs
using Entity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System.Data;
using Web.Docentes.Models;

namespace Web.Docentes.Controllers
{
    public class DocenteController : Controller
    {
        public IActionResult Index(string Buscar = "", int? pagenumber = 1)
        {
            if (string.IsNullOrWhiteSpace(Buscar)) Buscar = "";

            List<DocenteE> ListadoDocente = new List<DocenteE>();
            ResultadoTransaccionE<DocenteE> resultado = new ResultadoTransaccionE<DocenteE>();
            try
            {
                resultado = ConsultaListaDocente(Buscar);
                if (resultado.IdRegistro > -1)
                {
                    ListadoDocente = resultado.DataList;
                }
            }
            catch (Exception ex) { }
            int pageSize = 3;

            return View(PaginatedList<DocenteE>.CreateAsync(ListadoDocente, pagenumber ?? 1, pageSize));
        }

        ResultadoTransaccionE<DocenteE> ConsultaListaDocente(string buscar)
        {
            ResultadoTransaccionE<DocenteE> resultado = new ResultadoTransaccionE<DocenteE>();
            try
            {
                var ruta = MetaGlobal.RutaApiVenta + MetaGlobal.RutaApiVentaRol + "/Listar_All?buscar=" + buscar;
                using (RestClient _client = new RestClient(ruta))
                {
                    RestRequest request = new RestRequest();
                    request.Method = Method.Get;
                    var response = _client.Execute(request);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var respuesta = JsonConvert.DeserializeObject<ResultadoTransaccionE<DocenteE>>(response.Content);
                        resultado.IdRegistro = respuesta.IdRegistro;
                        resultado.Mensaje = respuesta.Mensaje; ;
                        resultado.DataList = respuesta.DataList;
                    }
                    else
                    {
                        resultado.IdRegistro = -1;
                        resultado.Mensaje = response.Content;
                    }
                }
            }
            catch (Exception ex)
            {
                resultado.IdRegistro = -1;
                resultado.Mensaje = ex.Message;
            }
            return resultado;
        }

        public IActionResult Create()
        {
            DocenteE objDocente = new DocenteE();
            return View(objDocente);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(DocenteE objDocente)
        {
            ViewBag.Mensaje = "";
            ViewBag.ErrorMensaje = "";

            if (ModelState.IsValid)
            {
                var resultado = RegistrarDocente(objDocente);
                if (resultado.IdRegistro == -1)
                {
                    ViewBag.ErrorMensaje = resultado.Mensaje;
                }
                else
                {
                    ViewBag.Mensaje = resultado.Mensaje;
                }
            }
            return View(objDocente);
        }

        ResultadoTransaccionE<string> RegistrarDocente(DocenteE obj)
        {
            ResultadoTransaccionE<string> resultado = new ResultadoTransaccionE<string>();
            try
            {
                var ruta = MetaGlobal.RutaApiVenta + MetaGlobal.RutaApiVentaRol + "/Registrar_Docente";
                var JsonData = JsonConvert.SerializeObject(obj);

                using (RestClient _client = new RestClient(ruta))
                {
                    RestRequest request = new RestRequest();
                    request.Method = Method.Post;
                    request.AddJsonBody(JsonData);
                    var response = _client.Execute(request);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var respuesta = JsonConvert.DeserializeObject<ResultadoTransaccionE<string>>(response.Content);
                        resultado.IdRegistro = respuesta.IdRegistro;
                        resultado.Mensaje = respuesta.Mensaje;
                    }
                    else
                    {
                        resultado.IdRegistro = -1;
                        resultado.Mensaje = response.Content;
                    }
                }
            }
            catch (Exception ex)
            {
                resultado.IdRegistro = -1;
                resultado.Mensaje = ex.Message;
            }
            return resultado;
        }
    }
}

Fronted/WEB/Web.Docentes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Docentes.Models;

namespace Web.Docentes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fronted/WEB/Web.Docentes/Views/Docente/Create.cshtml
@using Entity
@model DocenteE

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row mt-3">
    <div class="col-2">
        <a asp-controller="Docente" asp-action="Index" class="btn btn-primary"> Regresar</a>
    </div>
    <div class="col-10">
        <label class="fw-bold">REGISTRAR DOCENTE</label>
    </div>
</div>

<div class="row mt-2">
    @if (!string.IsNullOrWhiteSpace(ViewBag.Mensaje))
    {
        <div class="alert alert-primary" role="alert">
            @ViewBag.Mensaje
        </div>
    }
    @if (!string.IsNullOrWhiteSpace(ViewBag.ErrorMensaje))
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.ErrorMensaje
        </div>
    }
</div>

<div class="row mt-2">
    <form asp-action="Create" asp-controller="Docente" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="card">
            <div class="card-header">
                Ingrese Datos
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        Nombres
                        <input type="text" asp-for="Nombres" class="form-control" />
                        <span asp-validation-for="Nombres" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Apellido Paterno
                        <input type="text" asp-for="ApellidoPaterno" class="form-control" />
                        <span asp-validation-for="ApellidoPaterno" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Apellido Materno
                        <input type="text" asp-for="ApellidoMaterno" class="form-control" />
                        <span asp-validation-for="ApellidoMaterno" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Nro. Documento
                        <input type="text" asp-for="NroDocumento" class="form-control" />
                        <span asp-validation-for="NroDocumento" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Fecha de Nacimiento
                        <input type="date" asp-for="FechaNacimiento" class="form-control" />
                        <span asp-validation-for="FechaNacimiento" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Direccion
                        <input type="text" asp-for="Direccion" class="form-control" />
                        <span asp-validation-for="Direccion" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Email
                        <input type="text" asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Nro. de Celular
                        <input type="text" asp-for="Celular" class="form-control" />
                        <span asp-validation-for="Celular" class="text-danger">Campo Obligatorio</span>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">Registrar</button>
            </div>
        </div>
    </form>
</div>

Fronted/WEB/Web.Docentes/Views/Docente/Index.cshtml
@using Entity
@model PaginatedList<DocenteE>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row mt-3">
    
</div>

<div class="row mt-2">
    <div class="card">
        <div class="card-header">
            <label class="fw-bold">Listado de Docentes</label>
        </div>
        <div class="card-body">

            <div class="row mt-3">
                <div class="col-6">
                    <form asp-controller="Docente" asp-action="Index">
                        Buscar Docente
                        <div class="row">
                            <div class="col-9">
                                <input type="text" class="form-control" name="Buscar" />
                            </div>
                            <div class="col-3">
                                <button class="btn btn-success">Buscar</button>
                            </div>

                        </div>
                    </form>
                </div>

                <div class="col-6 text-end">
                    <a asp-action="Create" asp-controller="Docente" class="btn btn-primary">Registrar Docente</a>
                </div>
            </div>
            <table class="table table-bordered table-striped mt-3">
                <thead>
                    <tr>
                        <th class="text-center">Cod. Docente</th>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Apellido Paterno</th>
                        <th class="text-center">Apellido Materno</</th>
                        <th class="text-center">Nro. Documento</</th>
                        <th class="text-center">Fecha de Nacimiento</</th>
                        <th class="text-center">Direccion</</th>
                        <th class="text-center">Email</</th>
                        <th class="text-center">Celular</</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count() > 0)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-center">@item.IdDocente</td>
                                <td class="text-center">@item.Nombres</td>
                                <td class="text-center">@item.ApellidoPaterno</td>
                                <td class="text-center">@item.ApellidoMaterno</td>
                                <td class="text-center">@item.NroDocumento</td>
                                <td class="text-center">@item.FechaNacimiento</td>
                                <td class="text-center">@item.Direccion</td>
                                <td class="text-center">@item.Email</td>
                                <td class="text-center">@item.Celular</td>
                            </tr>
                        }
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4">
                            <label class="fw-bold">Total de registros: </label> @Model.Count().ToString()
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            @{
                                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                            }

                            <a asp-action="Index"
                               asp-route-pagenumber="@(Model.PageIndex - 1)"
                               class="btn btn-default @prevDisabled">
                                Previous
                            </a>
                            <a asp-action="Index"
                               asp-route-pagenumber="@(Model.PageIndex + 1)"
                               class="btn btn-default @nextDisabled">
                                Next
                            </a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

Fronted/WEB/Web.Docentes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Fronted/WEB/Web.Docentes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.Docentes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.Docentes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web.Docentes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Docente" asp-action="Index">Docente</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web.Docentes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>